name: E2E Tests CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Descargar el código del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24
          cache: "npm"

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Instalar navegadores de Playwright
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # 5️⃣ Ejecutar los tests de Cucumber
      - name: Run Cucumber tests
        run: |
           npx cucumber-js --format json:cucumber-report.json 
           

      - name: Check generated files
        run: ls -la


      # 6️⃣ Generar reporte HTML
      - name: Generate HTML report
        run: node generate-report.js

      # 7️⃣ Subir el reporte HTML como artifact
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: cucumber-report.html
